name: Docker Dev Staging Images Build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: lc-dev-staging-api
          - target: node
            file: Dockerfile
            image_name: lc-dev-staging
    uses: ./.github/workflows/docker-multiarch.yml
    with:
      target: ${{ matrix.target }}
      file: ${{ matrix.file }}
      image_name: ${{ matrix.image_name }}
      dockerhub: true
      tags: |
        ${{ github.sha }}
        latest
    secrets: inherit
