name: Docker Dev Images Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - 'Dockerfile.multi'

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: librechat-dev-api
          - target: node
            file: Dockerfile
            image_name: librechat-dev
    uses: ./.github/workflows/docker-multiarch.yml
    with:
      target: ${{ matrix.target }}
      file: ${{ matrix.file }}
      image_name: ${{ matrix.image_name }}
      tags: |
        ${{ github.sha }}
        latest
    secrets: inherit
