name: Docker Dev Branch Images Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'api/**'
      - 'client/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - 'Dockerfile.multi'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: lc-dev-api
          - target: node
            file: Dockerfile
            image_name: lc-dev
    uses: ./.github/workflows/docker-multiarch.yml
    with:
      target: ${{ matrix.target }}
      file: ${{ matrix.file }}
      image_name: ${{ matrix.image_name }}
      dockerhub: true
      tags: |
        ${{ github.sha }}
        latest
    secrets: inherit
